# Generated by Django 2.2.1 on 2019-05-08 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_areasinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreasInfo',
            new_name='AreaInfo',
        ),
    ]
