# Generated by Django 2.2.1 on 2019-05-09 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20190509_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areainfo',
            old_name='area_parernt',
            new_name='area_parent',
        ),
    ]
